# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║                      CANONICAL SOURCE — kidecon-hub                         ║
# ╠══════════════════════════════════════════════════════════════════════════════╣
# ║                                                                            ║
# ║  THIS IS THE CANONICAL LOCATION. ALL EDITS TO LLM CLIENT CODE MUST BE      ║
# ║  MADE HERE AND ONLY HERE.                                                  ║
# ║                                                                            ║
# ║  The kidecon-agent repo holds a VENDORED COPY. That copy is READ-ONLY.     ║
# ║  Sync direction: hub ──► agent  (not the reverse).                         ║
# ║                                                                            ║
# ║  To push changes to the agent:  make sync-llm                              ║
# ║  To verify the agent is in sync: make check-llm-sync                       ║
# ║                                                                            ║
# ║  If you are in kidecon-agent and reading this: DO NOT EDIT THIS FILE.      ║
# ║  Go to kidecon-hub/shared/llm_clients/ to make your change.                ║
# ║                                                                            ║
# ╚══════════════════════════════════════════════════════════════════════════════╝
import logging

from shared.llm_clients.base import BaseLLMProvider
from shared.llm_clients.base import LLMProviderError
from shared.llm_clients.deepseek_provider import DeepSeekProvider
from shared.llm_clients.factory import LLMClientFactory
from shared.llm_clients.openrouter_provider import OpenRouterProvider
from shared.llm_clients.tiers import TierRouter
from shared.llm_clients.together_provider import TogetherProvider

logger = logging.getLogger(__name__)

__all__ = [
    "BaseLLMProvider",
    "DeepSeekProvider",
    "LLMClientFactory",
    "LLMProviderError",
    "OpenRouterProvider",
    "TierRouter",
    "TogetherProvider",
]
